### ISSUE TITLE
Marks of HuskHomes are not showing in BlueMap on Fabric

### ISSUE THREAD

**Issue by foxii-cn** [WiIIiam278/HuskHomes#453]
It appears that warps and public homes of HuskHomes are not showing in BlueMap under the Fabric platform, and there is no related information in the backend log. I'm sure they are all turned on in the configuration file. I will provide more tests and screenshots later.
<html>
<body>

environment | version
-- | --
Java | azul/prime:17
HuskHomes | 4.4.1
Fabric | 0.14.21
Minecraft | 1.20.1
BlueMap | 3.14

</body>
</html>

**Comment by foxii-cn** [comment]
1. Create a brand new Fabric server and add the latest version mods
2. Modify the configuration file `.\config\bluemap\core.conf`
```
accept-download: true
```
3. Create warp and phome.
![image](https://github.com/WiIIiam278/HuskHomes/assets/38043552/885963f4-107d-4a48-a470-6ac5c37238c9)
5. Restart the server. The map hook setting for HuskHomes is enabled by default.
```
map_hook:
  # Display public homes/warps on your Dynmap, BlueMap or Pl3xMap. Docs: https://william278.net/docs/huskhomes/map-hooks
  enabled: true
  # Show public homes on the web map
  show_public_homes: true
  # Show warps on the web map
  show_warps: true
```
6. No markers here.
![image](https://github.com/WiIIiam278/HuskHomes/assets/38043552/a01088e5-8675-4f0c-ae02-4c3e68504c8a)

Did I miss anything?
