### ISSUE TITLE
[BUG] The actual reading behavior of the configuration file does not match the generated default configuration file

### ISSUE THREAD

**Issue by Ghost-chu** [WiIIiam278/HuskHomes#471]
Related to: https://github.com/WiIIiam278/HuskHomes/blob/e7c95ee7423157d5c4d729a758bbc40062621126/common/src/main/java/net/william278/huskhomes/config/Settings.java#L367C69-L367C82

HuskHomes generated, it won't work.
```yaml
table_names:
    PLAYER_COOLDOWNS_DATA: huskhomes_mondstadt_user_cooldowns
    POSITION_DATA: huskhomes_mondstadt_position_data
    WARP_DATA: huskhomes_mondstadt_warps
    PLAYER_DATA: huskhomes_mondstadt_users
    SAVED_POSITION_DATA: huskhomes_mondstadt_saved_positions
    HOME_DATA: huskhomes_mondstadt_homes
    TELEPORT_DATA: huskhomes_mondstadt_teleports
```

If you change it to lower case, it will work.

```yaml
table_names:
    player_cooldowns_data: huskhomes_mondstadt_user_cooldowns
    position_data: huskhomes_mondstadt_position_data
    warp_data: huskhomes_mondstadt_warps
    player_data: huskhomes_mondstadt_users
    saved_position_data: huskhomes_mondstadt_saved_positions
    home_data: huskhomes_mondstadt_homes
    teleport_data: huskhomes_mondstadt_teleports
```
