### ISSUE TITLE
rtp command not working with no error message

### ISSUE THREAD

**Issue by dchurch315** [WiIIiam278/HuskHomes#529]
I haven't used RTP in a while but I am fairly sure it was working in previous version. Issuing rtp now puts up message saying "Finding a safe random position to teleport you to" which fades without ever sending you anywhere, no error and no money withdrawn from economy. No errors in server console either.

Relevant lines in config.yml
```
rtp:
  # Radius around the spawn point in which players cannot be random teleported to
  radius: 256
  # Radius of the spawn area in which players cannot be random teleported to
  spawn_radius: 4096
  # Mean of the normal distribution used to calculate the distance from the center of the world
  distribution_mean: 0.75
  # Standard deviation of the normal distribution for distributing players randomly
  distribution_deviation: 2.0
  # List of worlds in which /rtp is disabled. Please note that /rtp does not work well in the nether.
  restricted_worlds:
  - world_nether
  - world_the_end
```

Server is Paper-1.20.2-243, Huskhomes 4.5.3

```
List of plugins
Paper Plugins:
- AdvancedServerList, HuskHomes
Bukkit Plugins:
- AureliumSkills, Chunky, Citizens, CommandHook, DecentHolograms, DungeonParties, EmeraldBank, FastAsyncWorldEdit, GriefPrevention, LevelledMobs, LuckPerms, MythicDungeons, Pl3xMap, Pl3xMap-Claims, PlayerKits2, ProtocolLib, QuickShop, Sentinel, SuperVanish, TangledMaze, Vault, ViaVersion, voicechat
```

Let me know if you need any other info.
