### ISSUE TITLE
Hook into LuckPerms to fix duplicate permission keying for better stack_permission_limits handling

### ISSUE THREAD

**Issue by triesharder** [WiIIiam278/HuskHomes#542]
## My setup
All players start with `huskhomes.max_homes.10` and they can improve their account by doing many tasks.

## The problem
There would be more than one in-game reward granting +1 home limit to the player;
LuckPerms will ignore duplicated permission nodes, so having two entries of `huskhomes.max_homes.1` will not do the trick

## My solution
**Named bonuses!** We define it the `config.yml` or in another file, your preference;
It would work as follows:
```yaml
bonuses:
  eventOne:
    max_homes: 1
  eventTwo:
    max_homes: 5
  veryImportantTask:
    max_homes: 42069
    max_public_homes: 12
```
Then we grant the player `huskhomes.bonuses.<eventName>`:
So i would have more flexibility to plan player limits

## Note
I just found out that doing 
![image](https://github.com/WiIIiam278/HuskHomes/assets/89689590/7975e665-0cd7-4047-a168-9cc3c02e4671)
works as i need it working, but not very classy nor organizated.

I appreaciate this plugin very much, i want to thank you again for making possible to bulk delete from specific worlds!
