### ISSUE TITLE
save_on_teleport_event does not appear to work as intended

### ISSUE THREAD

**Issue by KermX** [WiIIiam278/HuskHomes#813]
**Description of the problem**
/back does not appear to actually save on teleport events. Back locations are not saved from other plugins despite them firing these events _(example, Towny)_

**Additional Info**
All cross server options are disabled.

**Versions**
Paper 1.21.4
Huskhomes 4.9.5

**General Settings Config**
```
general:
  max_homes: 1
  max_public_homes: 0
  home_delimiter: .
  stack_permission_limits: false
  permission_restrict_warps: false
  teleport_warmup_time: 0
  teleport_warmup_cancel_on_damage: false
  teleport_warmup_cancel_on_move: false
  teleport_warmup_display: NONE
  teleport_invulnerability_time: 0
  teleport_request_expiry_time: 60
  strict_tpa_here_requests: true
  list_items_per_page: 12
  always_respawn_at_spawn: true
  teleport_async: true
  names:
    overwrite_existing: true
    case_insensitive: false
    restrict: true
    regex: '[a-zA-Z0-9-_]*'
  descriptions:
    restrict: false
    regex: \A\p{ASCII}*\z
  back_command:
    return_by_death: true
    save_on_teleport_event: true
    restricted_worlds:
    - mob_arena
  sound_effects:
    enabled: true
    types:
      TELEPORTATION_COMPLETE: entity.enderman.teleport
      TELEPORTATION_WARMUP: block.note_block.banjo
      TELEPORTATION_CANCELLED: entity.item.break
      TELEPORT_REQUEST_RECEIVED: entity.experience_orb.pickup
```
